
//  Color Palette by Paletton.com
//  Palette URL: http://paletton.com/#uid=b1u0F3D0kX0AXTw5sOekKrdP9gnQe


// Primary color:
export const primary = {
   normal: '#FFD900',
   darker2: '#2B2500',
   darker1: '#A58C00',
   lighter1: '#FFDE26',
   lighter2: '#FFEB7D',
}

//   shade 0 = #FFD900 = rgb(255,217,  0) = rgba(255,217,  0,1) = rgb0(1,0.851,0)
//   shade 1 = #2B2500 = rgb( 43, 37,  0) = rgba( 43, 37,  0,1) = rgb0(0.169,0.145,0)
//   shade 2 = #A58C00 = rgb(165,140,  0) = rgba(165,140,  0,1) = rgb0(0.647,0.549,0)
//   shade 3 = #FFDE26 = rgb(255,222, 38) = rgba(255,222, 38,1) = rgb0(1,0.871,0.149)
//   shade 4 = #FFEB7D = rgb(255,235,125) = rgba(255,235,125,1) = rgb0(1,0.922,0.49)

// Secondary color (1):
export const accent = {
   normal: '#FF8C00',
   darker2: '#2B1800',
   darker1: '#A55B00',
   lighter1: '#FF9E26',
   lighter2: '#FFC47D',
}

//   shade 0 = #FF8C00 = rgb(255,140,  0) = rgba(255,140,  0,1) = rgb0(1,0.549,0)
//   shade 1 = #2B1800 = rgb( 43, 24,  0) = rgba( 43, 24,  0,1) = rgb0(0.169,0.094,0)
//   shade 2 = #A55B00 = rgb(165, 91,  0) = rgba(165, 91,  0,1) = rgb0(0.647,0.357,0)
//   shade 3 = #FF9E26 = rgb(255,158, 38) = rgba(255,158, 38,1) = rgb0(1,0.62,0.149)
//   shade 4 = #FFC47D = rgb(255,196,125) = rgba(255,196,125,1) = rgb0(1,0.769,0.49)

// Secondary color (2):
export const additional = {
   normal: '#0251B8',
   darker2: '#010D1C',
   darker1: '#04326C',
   lighter1: '#317DDF',
   lighter2: '#78A6E2',
}

//   shade 0 = #0251B8 = rgb(  2, 81,184) = rgba(  2, 81,184,1) = rgb0(0.008,0.318,0.722)
//   shade 1 = #010D1C = rgb(  1, 13, 28) = rgba(  1, 13, 28,1) = rgb0(0.004,0.051,0.11)
//   shade 2 = #04326C = rgb(  4, 50,108) = rgba(  4, 50,108,1) = rgb0(0.016,0.196,0.424)
//   shade 3 = #317DDF = rgb( 49,125,223) = rgba( 49,125,223,1) = rgb0(0.192,0.49,0.875)
//   shade 4 = #78A6E2 = rgb(120,166,226) = rgba(120,166,226,1) = rgb0(0.471,0.651,0.886)


//  Generated by Paletton.com (c) 2002-2014
